config.load_autoconfig()

config.bind('sbd', 'spawn /home/cpulley/.scripts/base64_decode')
config.bind('sfm', 'hint links spawn smplayer -fullscreen -close-at-end {hint-url}')
config.bind('sm', 'spawn smplayer -fullscreen -close-at-end {url}')
config.bind('sfyd', 'hint links spawn youtube-dl --output "/home/cpulley/Downloads/%(title)s.%(ext)s" {hint-url}')
config.bind('sfya', 'hint links spawn youtube-dl -x --audio-format mp3 --output "/home/cpulley/Downloads/%(title)s.%(ext)s" {hint-url}')
config.bind('syd', 'spawn youtube-dl --output "/home/cpulley/Downloads/%(title)s.%(ext)s" {url}')
config.bind('sya', 'spawn youtube-dl -x --audio-format mp3 --output "/home/cpulley/Downloads/%(title)s.%(ext)s" {url}')
config.bind('sy', 'hint links spawn youtube-dl')
config.bind('yf', 'hint links yank')
config.bind('m', 'set-cmd-text -s :bookmark-load')
config.bind('M', 'set-cmd-text -s :bookmark-load -t')
config.bind('wm', 'set-cmd-text -s :bookmark-load -w')
config.bind('<ctrl-i>', 'enter-mode passthrough')
config.bind('<ctrl-b>', 'quickmark-save')
config.bind('<ctrl-m>', 'bookmark-add')
config.bind('<alt-b>', 'set-cmd-text -s :quickmark-del')
config.bind('<alt-m>', 'set-cmd-text -s :bookmark-del')

config.unbind('sf', mode='normal')
config.unbind('sk', mode='normal')
config.unbind('sl', mode='normal')
config.unbind('ss', mode='normal')
config.unbind('<ctrl-v>', mode='normal')
