#! /bin/sh

#############################################
#                _                          #
#     /\        | |                         #
#    /  \  _   _| |_ ___  _ __ _   _ _ __   #
#   / /\ \| | | | __/ _ \| '__| | | | '_ \  #
#  / ____ \ |_| | || (_) | |  | |_| | | | | #
# /_/    \_\__,_|\__\___/|_|   \__,_|_| |_| #
#                                           #
#############################################

# Add wallpaper
sh ~/.fehbg &
sxhkd &

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Set capslock button to escape
setxkbmap -option caps:escape &

# Enable wallpaper
sh ~/.fehbg & 

# Get audio running early
pulseaudio --start

# Enable notifications via Dunst
dunst & 
mpd_notifyd &

# Compositing! Woo!
compton &

# These should only launch on desktop
polybar DVI-D-0 &
polybar HDMI-0 &
polybar VGA-0 &

# This should only launch on laptop
polybar LVDS1 &

########################################### 
#   _____      _   _   _                  #
#  / ____|    | | | | (_)                 #
# | (___   ___| |_| |_ _ _ __   __ _ ___  #
#  \___ \ / _ \ __| __| | '_ \ / _` / __| #
#  ____) |  __/ |_| |_| | | | | (_| \__ \ #
# |_____/ \___|\__|\__|_|_| |_|\__, |___/ #
#                              |___/      #
#                                         #
########################################### 

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config normal_border_color \#E0E0E0
bspc config active_border_color \#E0E0E0
bspc config focused_border_color \#4D4D4C
bspc config presel_feedback_color \#999999

bspc monitor DVI-D-0 -d DVI
bspc monitor HDMI-0 -d HDMI
bspc monitor VGA-0 -d VGA
bspc monitor LVDS1 -d LVDS1

bspc config bottom_padding 20
bspc config top_padding 2

#############################
#  _____       _            #
# |  __ \     | |           #
# | |__) |   _| | ___  ___  #
# |  _  / | | | |/ _ \/ __| #
# | | \ \ |_| | |  __/\__ \ #
# |_|  \_\__,_|_|\___||___/ #
#                           #
#############################

bspc rule -a Steam state=tiled
bspc rule -a Oblogout state=fullscreen follow=on monitor=DVI-D-0
