#!/bin/bash

DESKTOP_NAME=$(i3-msg -t get_workspaces | tr , '\n' | grep name | cut -d \" -f 4 | rofi -dmenu -location 7 -font 'Hack 6.5' -padding 10 -p 'Desktop: ' -width 250 -i -lines 5 -hide-scrollbar)

if [ -z "$DESKTOP_NAME" ]; then
    exit 0
fi

i3-msg workspace "$DESKTOP_NAME"
