#!/bin/bash

DESKTOP_NAME=$(echo '' | rofi -dmenu -fuzzy -font 'Hack 12' -padding 10 -p 'Rename: ' -width 500 -i -lines -color-normal '#eeeeee,#4d4d4d,#eeeeee,#eeeeee,#4d4d4d' -hide-scrollbar)

i3-msg "rename workspace to \"$DESKTOP_NAME\""
