#!/bin/bash

# Kill all existing polybar instances
killall polybar

# Wait for i3 to finish reloading
sleep 1

# Restart polybar so it updates properly
polybar DVI-D-0 &
polybar HDMI-0 &
polybar VGA-0 &
polybar LVDS1 &

exit 0
