#!/bin/bash

# Kill all existing polybar instances
killall polybar

# Restart polybar so it updates properly
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload bspwmbar &
  done
else
  polybar --reload bspwmbar &
fi

exit 0
