#!/bin/bash

# This script is used to make my laptop's backlight keys
# move on more of a sliding scale.
# Pretty simple, just call it with -inc or -dec using
# i3 or sxhkd or whatever.

backlight=$(xbacklight | cut -d '.' -f 1)

if [[ $1 == "-inc" ]]; then
	if   (( $backlight < 2 )); then
		xbacklight -time 75 -inc 1
	elif (( $backlight < 10 )); then
		xbacklight -time 75 -inc 2
	elif (( $backlight < 20 )); then
		xbacklight -time 75 -inc 5
	else
		xbacklight -time 75 -inc 10
	fi
elif [[ $1 == "-dec" ]]; then
	if   (( $backlight >=  20 )); then
		xbacklight -time 75 -dec 10
	elif (( $backlight >= 10 )); then
		xbacklight -time 75 -dec 5
	elif (( $backlight >= 2 )); then
		xbacklight -time 75 -dec 2
	else
		xbacklight -time 75 -set 1
	fi
fi
