#!/bin/bash

DESKTOP_NAME=`echo '' | rofi -dmenu -location 7 -fuzzy -font 'Hack 7' -padding 10 -p 'Rename: ' -width 250 -i -lines 1`
if [ -z $DESKTOP_NAME ]; then
    exit 0
fi

bspc desktop -n "$DESKTOP_NAME"
