#!/bin/bash

DMENU_NF="#A3A6AB"
DMENU_NB="#34322E"
DMENU_SF="#F6F9FF"
DMENU_SB="#5C5955"

DESKTOP_NAME=`bspc wm -d | jshon -e monitors -a -e desktops -a -e name -u | rofi -dmenu -location 7 -font 'Hack 7' -padding 10 -p 'Desktop: ' -width 250 -i -lines 5`

if [ -z $DESKTOP_NAME ]; then
    exit 0
fi

for existing_desktop in `bspc wm -d | jshon -e monitors -a -e desktops -a -e name -u`; do
    if [ "$DESKTOP_NAME" == "$existing_desktop" ]; then
        bspc desktop -f "$DESKTOP_NAME"
        exit 0
    fi
done

bspc monitor -a "$DESKTOP_NAME"
bspc desktop -f "$DESKTOP_NAME"
