#!/bin/bash

if [ $# -eq 0 ]; then
  if [ "$(ls ./*.pkg.tar.xz)" ]; then
    echo "Preparing to install:"
    ls -1 ./*.pkg.tar.xz
    if sudo pacman -U ./*.pkg.tar.xz; then
      cp ./*.pkg.tar.xz ~/.build/.cache/
    fi
  else
    echo "No valid packages found!"
  fi
else
  for TARGET in "$@"
  do
    if [ -f "$TARGET" ] && [[ "$TARGET" = *.pkg.tar.xz ]]; then
      if sudo pacman -U "$TARGET"; then
        cp "$TARGET" ~/.build/.cache/
      fi
    else
      echo "$TARGET is not a valid package!"
    fi
  done
fi
