#!/usr/bin/bash

# Define options for menu
menu="Lock Logout Suspend Restart Shutdown"

# Define commands for menu
Shutdown="systemctl poweroff"
Suspend="systemctl suspend"
Restart="systemctl reboot"
Logout="i3-msg exit"
Lock="light-locker-command -l"

# Launch Rofi
choice=$(echo -e "$menu" | rofi -dmenu -fuzzy -i -sep ' ' -p 'Logout Menu: ' -theme ~/.config/rofi/default.rasi)

# Run variable selected at lines 7-11
eval "\$$choice"
