#!/bin/bash

if [ $# -eq 0 ];
then echo "Usage: laur (package name)"
	 exit 1
fi

for PACKAGE in "$@"
do
		if [ $(cower -sb $PACKAGE | grep -c 'aur/'$PACKAGE'\ ') -eq 1 ]
		then
				echo ':: Removing ~/.build/local/'$PACKAGE
				rm -rf ~/.build/local/$PACKAGE
				cower -ft ~/.build/local -d $PACKAGE
		else
				echo ':: Unable to find '\'$PACKAGE\''! Skipping...'
		fi
done

exit 0
