#!/usr/bin/bash

# Suppress stderr for polybar
exec 2> /dev/null

if  playerctl status | grep Playing > /dev/null
then echo '  '$(playerctl metadata artist && echo ' - ' && playerctl metadata title)
else echo
fi

exit 0
